### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by HenningKlokkeraasen** [jackfagner/OpenTidl#2]
Hi, sorry for creating an issue - it's the only way to contact a user.
First - thank you very much for open sourcing this library. I am using it in a couple of projects now. It is really great!
Would you consider publishing it to NuGet.org, or another NuGet host (e.g. MyGet?)
It would make it easier to create projects that depend on OpenTidl.
If not - would you mind if I publish my forked version?

**Comment by jackfagner** [comment]
Good idea. I'll publish "official" OpenTidl to GitHub soon.
You may of course publish your fork as well, but to avoid confusion I would recommend you to change the name and preferably also provide a somewhat different feature set (i.e. add some enhancements to differentiate the projects).

**Comment by HenningKlokkeraasen** [comment]
Great!
Btw - you might want to parameterize the API token - otherwise the one hardcoded in ClientConfiguration might be heavily used and perhaps blocked by Tidal due to too much traffic. Not sure they have such a restriction but I guess it could happen. Which would probably mean turning ClientConfiguration.Default into a method with the token as a parameter? Drawback would be that it's less easy to get going, and a breaking change.

**Comment by jackfagner** [comment]
If I recall correctly, the token is a constant that only changes with a new client release (Android). I.e. Android client v1.10.2 always use token "kgsOOm..". The ClientUniqueKey, on the other hand, should be unique per client (go figure).

**Comment by HenningKlokkeraasen** [comment]
Aha, I see. Good to know, thanks!
