### ISSUE TITLE
ETag/If-None-Match Header

### ISSUE THREAD

**Issue by scgough** [jackfagner/OpenTidl#3]
Hi,
Great API. I've noticed an issue when I try and add a track to an existing playlist. This might affect any POST request but I've not tested fully as yet. 

It looks like the request to add the track needs the `If-None-Match` header adding in. Without it the request fails. 

The value of this _seems_ to be the `ETag` value given when a playlist is requested via `GetPlaylist`.

**Comment by scgough** [comment]
Update - I do see a reference to the `IfNoneMatch` variable on `AddPlaylistTracks` and `DeletePlaylistTracks` so maybe this is a work in progress?

**Comment by jackfagner** [comment]
Thank you for reporting this bug. IfNoneMatch is most likely used as a timestamp-based concurrency control and I wasn't aware it was mandatory for the playlist methods. An update is coming ...

**Comment by scgough** [comment]
Great thank you, I've managed to implement this my side by extracting the `ETag` header to the `ModelBase` (where available) then passing it through to the relevant requests as a custom header variable on the `RestClient.Process` method.

**Comment by jackfagner** [comment]
Sounds good. You are much welcome to create a pull request.

**Comment by jackfagner** [comment]
This issue should be fixed in 2282d9978587a65579ae9855e07ae305e89ba0a4
