### ISSUE TITLE
Playlist Visibility

### ISSUE THREAD

**Issue by scgough** [jackfagner/OpenTidl#4]
Hi,
Me again! I'm noticing that although my request to change the visibility of a playlist between `Public` and `Private` is seemingly successful, the setting isn't actually reflected at all when I reload the Playlist. 

I have the custom method added in the `OpenTidlSession` class:

```
public async Task<EmptyModel> UpdatePlaylistVisibility(String playlistUuid, bool isPublic, string ifNoneMatch = "")
        {
            Dictionary<string, string> additionalHeaders = new Dictionary<string, string>();
            if (ifNoneMatch != String.Empty)
            {
                additionalHeaders.Add("If-None-Match", ifNoneMatch);
            }

            return HandleResponse(await RestClient.Process<EmptyModel>(
                RestUtility.FormatUrl("/playlists/{uuid}", new
                {
                    uuid = playlistUuid
                }), new
                {
                    sessionId = SessionId,
                    countryCode = CountryCode
                }, new
                {
                    publicPlaylist = isPublic
                }, "POST", additionalHeaders));
        }
```

Have you managed to successfully switch public/private on a playlist? I'm wondering if the request needs to be a `PATCH` or `PUT` request? Like I say, the above gives me a `200 OK` response but the change isn't reflected at all.

**Comment by jackfagner** [comment]
Unfortunately, I haven't tested this feature. I have only implemented features available in the Android client (... a year ago). If you intercept the traffic of the official Android or web client you should get all the parameters needed, as well as what HTTP method (POST/PATCH/PUT) to use.
Are there other features, beside playlist visibility, that you know are missing in this API? If so, please provide a list and I'll try to add them.

**Comment by scgough** [comment]
ok, i'll take a look at this. the website doesn't actually seem to have a public/private switch on it

**Comment by scgough** [comment]
Not 100% confirmed but it would seem that Tidal don't allow user created playlists to be `Public` and searchable via their app. Crazy! 
All the playlists in the app (outside of My Music) seem to be curated by Tidal themselves.

**Comment by jackfagner** [comment]
Yes, it seems `public` = created by TIDAL and `private`= created by user (you). I'm closing this issue since it's a limit in TIDALs system, not in this API.
