### ISSUE TITLE
Examples or simple documentation - please

### ISSUE THREAD

**Issue by mvarchdev** [jackfagner/OpenTidl#9]
Hello. I am writing this request because I want to use this epic repo in my big project, the project will be based on playing songs in the one jukebox virtual room which will be controlled by multiple people.

But, I cannot find how the Tidal authorization system works, so I cannot assume how this repo works. Please, can you help?

It would be really great.

Thanks in advance.

**Comment by jackfagner** [comment]
I actually have no idea if this code works anymore. I am not using Tidal and don't have any valid credentials. Sorry.
